version: '3'

tasks:
  test:
    preconditions:
      - sh: gotestsum --version
        msg: install with "go install gotest.tools/gotestsum@latest"
    cmds:
      - defer: rm coverage.out
      - >
        gotestsum --format pkgname --
        -covermode=atomic
        -coverprofile=coverage.out
        ./...
  run: go run ./test/... {{ .CLI_ARGS }}